//! Unit-test entry point.
//!
//! Imports every module that contains `test` blocks so
//! `zig build test` discovers them.

const std = @import("std");

comptime {
    _ = @import("util/ring.zig");
    _ = @import("util/utf8.zig");
    _ = @import("util/percent.zig");
    _ = @import("util/pathz.zig");
    _ = @import("util/shellquote.zig");
    _ = @import("util/humantype.zig");
    _ = @import("util/platform.zig");
    _ = @import("util/shellintegration.zig");
    _ = @import("util/png.zig");
    _ = @import("util/marks.zig");
    _ = @import("util/gifrec.zig");
    _ = @import("util/webm.zig");
    _ = @import("util/videorec.zig");
    _ = @import("util/churn.zig");
    _ = @import("util/content.zig");
    _ = @import("util/yuv.zig");
    _ = @import("shim_drift_test.zig");
    _ = @import("mux/predict.zig");
    _ = @import("mux/kitty_inline.zig");
    _ = @import("parser/event.zig");
    _ = @import("parser/vt.zig");
    _ = @import("parser/conformance_test.zig");
    _ = @import("parser/screen_conformance_test.zig");
    _ = @import("parser/wezterm_conformance_test.zig");
    _ = @import("grid/cell.zig");
    _ = @import("grid/style_pool.zig");
    _ = @import("grid/screen.zig");
    _ = @import("grid/selection.zig");
    _ = @import("grid/selection_conformance_test.zig");
    _ = @import("grid/image_store.zig");
    _ = @import("grid/reflow.zig");
    _ = @import("grid/reflow_screen_test.zig");
    _ = @import("grid/url_scan.zig");
    _ = @import("grid/word_motion.zig");
    _ = @import("layout.zig");
    _ = @import("shader_preset.zig");
    _ = @import("layout_simple.zig");
    _ = @import("parser/sixel.zig");
    _ = @import("parser/iterm_image.zig");
    _ = @import("parser/kitty_image.zig");
    _ = @import("ui/input.zig");
    _ = @import("ui/tree.zig");
    _ = @import("ui/hints.zig");
    _ = @import("ui/pane.zig");
    _ = @import("ui/tab_effects.zig");
    // The browser facade only re-exports a few decls, which is NOT
    // enough to pull its package's tests in: a test block in one of
    // these modules silently never runs unless the file is referenced
    // here by name. Proven with a deliberately failing canary.
    _ = @import("ui/browser.zig");
    _ = @import("ui/browser/view.zig");
    _ = @import("ui/browser/types.zig");
    _ = @import("ui/browser/conn.zig");
    _ = @import("ui/browser/render.zig");
    _ = @import("ui/browser/nav.zig");
    _ = @import("ui/browser/locbar.zig");
    _ = @import("ui/browser/tabs.zig");
    _ = @import("ui/browser/menu.zig");
    _ = @import("ui/browser/ops.zig");
    _ = @import("ui/browser/jobs.zig");
    _ = @import("ui/browser/jobpanel.zig");
    _ = @import("ui/browser/open.zig");
    _ = @import("ui/browser/preview.zig");
    _ = @import("ui/browser/props.zig");
    _ = @import("ui/browser/places.zig");
    _ = @import("ui/browser/search.zig");
    _ = @import("ui/browser/compare.zig");
    _ = @import("ui/browser/gitstat.zig");
    _ = @import("ui/browser/views.zig");
    _ = @import("ui/browser/selection.zig");
    _ = @import("a11y/view.zig");
    _ = @import("a11y/nsax.zig");
    _ = @import("ipc/protocol.zig");
    _ = @import("ipc/mux_cli.zig");
    _ = @import("ipc/keys.zig");
    _ = @import("ipc/termdrive.zig");
    _ = @import("ipc/appdrive.zig");
    _ = @import("ipc/cdp.zig");
    _ = @import("ipc/mcp.zig");
    _ = @import("ipc/evkeys.zig");
    _ = @import("ipc/xkblayout.zig");
    _ = @import("ipc/mcpassets.zig");
    _ = @import("util/template.zig");
    _ = @import("util/ocr.zig");
    _ = @import("util/mounts.zig");
    _ = @import("render/bg_pass.zig");
    _ = @import("mux/wire.zig");
    _ = @import("mux/fsserve.zig");
    _ = @import("mux/fsjob.zig");
    _ = @import("mux/fsjournal.zig");
    _ = @import("ipc/fsdrive.zig");
    _ = @import("ipc/fstransfer.zig");
    _ = @import("filebrowser/model.zig");
    _ = @import("filebrowser/cache.zig");
    _ = @import("filebrowser/emblems.zig");
    _ = @import("filebrowser/places.zig");
    _ = @import("filebrowser/thumbs.zig");
    _ = @import("filebrowser/transfers.zig");
    _ = @import("filebrowser/paths.zig");
    _ = @import("filebrowser/crumbs.zig");
    _ = @import("filebrowser/format.zig");
    _ = @import("filebrowser/progress.zig");
    _ = @import("filebrowser/xferqueue.zig");
    _ = @import("filebrowser/desktop.zig");
    _ = @import("filebrowser/hexdump.zig");
    _ = @import("filebrowser/previewers.zig");
    _ = @import("filebrowser/grouping.zig");
    _ = @import("filebrowser/viewmem.zig");
    _ = @import("filebrowser/registers.zig");
    _ = @import("fsmount.zig");
    _ = @import("mux/log.zig");
    _ = @import("mux/logring.zig");
    _ = @import("mux/pulse.zig");
    _ = @import("mux/wavcap.zig");
    _ = @import("mux/opuscodec.zig");
    _ = @import("mux/dmabuf_egl.zig");
    _ = @import("mux/snapshot.zig");
    _ = @import("mux/shell.zig");
    _ = @import("mux/desktop.zig");
    _ = @import("mux/icons.zig");
    _ = @import("mux/dbus.zig");
    _ = @import("mux/a11yhub.zig");
    _ = @import("mux/cast.zig");
    _ = @import("mux/rudp.zig");
    _ = @import("render/atlas_test.zig");
    _ = @import("render/atlas.zig");
    _ = @import("render/cell_pass.zig");
    _ = @import("render/style.zig");
    _ = @import("ui/input_conformance_test.zig");
    _ = @import("parser/multicell_conformance_test.zig");
    _ = @import("parser/clipboard_conformance_test.zig");
    _ = @import("parser/graphics_conformance_test.zig");
    _ = @import("config.zig");
    _ = @import("remoteapp.zig");
    _ = @import("grid/kitty_images.zig");
    _ = @import("grid/kitty_placeholder.zig");
    _ = @import("grid/image_pipeline_test.zig");
    _ = @import("grid/bidi.zig");
    _ = @import("grid/schemes.zig");
    _ = @import("wlhost/wire.zig");
    _ = @import("wlhost/dmabuf.zig");
    _ = @import("wlhost/protocol.zig");
    _ = @import("wlhost/track.zig");
    _ = @import("wlhost/pipe.zig");
    _ = @import("wlhost/compositor.zig");
    _ = @import("wlhost/zpool.zig");
    _ = @import("wlhost/pixcodec.zig");
    _ = @import("wlhost/vcodec.zig");
    _ = @import("winstream/proto.zig");
    _ = @import("winstream/source.zig");
    _ = @import("winstream/keymap.zig");
    _ = @import("remote_window.zig");
    _ = @import("terminal.zig");
}

test {
    std.testing.refAllDecls(@This());
}
